# Replacing Special Characters
- This step has been done in order to load the csv in SQL Workbench. Unfortunately, it is not able to read the file with accented letters.

## IMPORT LIBRARIES

In [2]:
import pandas as pd

In [3]:
all = pd.read_csv(r'./../data/cleaned_data/filtered_all.csv')

In [9]:
def change_char(df):
    """Function to replace special characters with normal alphabet"""
    special_characters = ["[àâä]","[éèêë]", "ï", "[öòóô]", "[ùûü]", "[²]", "[’]", "[°]"]
    replace = ["a", "e", "i", "o", "u", "2", "'", ""]

    for s, r in zip(special_characters, replace):
        for column in df.columns:
            df[column] = df[column].replace(s, r, regex=True)
    
    return df

In [11]:
all_new = change_char(all)

In [12]:
all_new

,link,img,product,color,brand,greenable,discounted,disc_price,orig_price,collection,label,gender,product_category,category
0,/en/product/denize-bubble-crepe-dress-sand-bel...,https://static.smallable.com/1686202-648x648q8...,denize bubble crepe dress,sand,bellepiece,0,1,139.3,199.0,ss,dress,w,long dresses,dress_overalls
1,/en/product/cabane-printed-shirt-blue-hartford...,https://static.smallable.com/1588974-648x648q8...,cabane printed shirt,blue,hartford,0,0,155.0,155.0,ss,top,w,long sleeve shirts,top
2,/en/product/garden-striped-cotton-poplin-top-b...,https://static.smallable.com/1677878-648x648q8...,garden striped cotton poplin top,blue,girls of dust,0,1,108.0,135.0,ss,top,w,short sleeve blouses,top
3,/en/product/tsikis-x-alma-deia-exclusive-blava...,https://static.smallable.com/1641315-648x648q8...,tsikis x alma deia exclusive - blava body chain,orange,alma deia,0,0,215.0,215.0,ss,underwear,w,necklaces,jewelry
4,/en/product/peggy-ibiza-striped-dress-yellow-t...,https://static.smallable.com/1669582-648x648q8...,peggy ibiza striped dress,yellow,the label edition,0,1,308.0,440.0,ss,dress,w,long dresses,dress_overalls
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5873,/en/product/ace-organic-cotton-t-shirt-adult-c...,https://static.smallable.com/1295099-648x648q8...,ace organic cotton t-shirt - adult collection,grey,wood wood,1,0,55.0,55.0,fw,top,m,"t-shirts, tops & blouses",top
5874,/en/product/chase-sweatshirt-navy-blue-carhart...,https://static.smallable.com/1297194-648x648q8...,chase sweatshirt,navy blue,carhartt wip,0,1,39.0,65.0,fw,top,m,"sweatshirts, sweaters",jumper
5875,/en/product/coda-jogger-black-avnier-210334,https://static.smallable.com/1181746-648x648q8...,coda jogger,black,avnier,0,1,54.0,90.0,fw,bottom,m,joggers,bottom
5876,/en/product/chase-t-shirt-navy-blue-carhartt-2...,https://static.smallable.com/1204364-648x648q8...,chase t-shirt,navy blue,carhartt wip,0,0,35.0,35.0,fw,top,m,"t-shirts, shirts",top
5877,/en/product/mohave-plain-bag-green-element-213741,https://static.smallable.com/1209522-648x648q8...,mohave plain bag,green,element,0,1,32.0,64.0,fw,bags,m,bags,bag

In [13]:
# save with encoding ascii required by sql and ignore any other errors from other special characters
all_new.to_csv("sql_csv.csv", index=False, encoding="ascii", errors="ignore")